- src/jellyfin.rs
Opening any media from an audio library while jellyfin-rpc is running causes it to crash because it was expecting an array with 4 times not 3 as is returned.
Also added support for displaying music information based on the audio media type.
> Audio Media Support

- src/main.rs
- src/services/jellyfin.rs
Added a log in the console to track whenever the media changes.
Fixed a crash where if discord was closed while jellyfin-rpc was still running, it wouldn't reconnect and crash instead.
Now exibits the same behavour as inital startup where it will attempt to reconnect on an exponential timer.
Tested with both Emby and Jellyfin for all media types.
> Fixed a crash when trying to reconnect

- scripts/Auto-install-macos.sh
- scripts/uninstall-macos.sh
Saw the invitation for someone to make a linux script to automate installation, hoped the offer extended to macOS as well.
I didn't do much in terms of UI, but it:
- creates the config file
- Asks user for all needed info
- Provides information on where to find needed values, akin to the readme.md instructions
- Confirms that the config file looks right before making any changes to the user's system
- downloads the program to the macOS binary folder
- curls the latest release & saves it to /usr/local/bin
- makes it executable
- Creates a Launch Agent so that the program can start itself at login and run in the background
- Saves the needed .plist and applies proper permissions
- Immediately loads jellyfin-rpc so that user doesn't have to log out & back in before it starts running
If I'm …
> Scripts to automate install/uninstall on macos

- Cargo.lock
- Cargo.toml
- src/core/config.rs
- src/main.rs
- src/services/imgur.rs
- src/services/jellyfin.rs
This PR has no functional changes but i feel it makes the code better to work with.
Removed unwraps in favor of expects and other things.
Simplified some functions in the MediaTypeVisitor.
Added a few comments where the code felt overly difficult to read.
Bumped version to 0.14.3
> Comments, error handling and readability

- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/services/jellyfin.rs
Changed `setactivity()` to account for no runtime.
Created new `MediaType::Book`, implemented into serialize, deserialize and from.
Updated README with new book type.
Version bump to 0.15.0
> Add support for books

- scripts/installer.py
I tried reinstalling the project on Windows yesterday but got `TypeError: 'function' object is not subscriptable`. I looked at the source code, and it turned out there's a missing round bracket when calling `subprocess.run`.
This PR fixes it by adding the missing round brackets.
> Fix subsprocess call missing round brackets on the installer

- src/services/jellyfin.rs
Before it would just break and try to display the image anyways, now it checks if the URL is returning an image or just some text before it tries displaying it.
> Fixed content that doesnt have images

- Cargo.lock
- jellyfin-rpc-cli/Cargo.toml
- jellyfin-rpc-cli/src/main.rs
- jellyfin-rpc-cli/src/updates.rs
- jellyfin-rpc/Cargo.toml
- jellyfin-rpc/src/core/config.rs
- jellyfin-rpc/src/core/error.rs
- jellyfin-rpc/src/lib.rs
- jellyfin-rpc/src/services/imgur.rs
- jellyfin-rpc/src/services/jellyfin.rs
Error handling on parts that would previously crash the entire program.
> Crash fixes

- jellyfin-rpc-cli/src/main.rs
- jellyfin-rpc/src/core/config.rs
- jellyfin-rpc/src/core/error.rs
- jellyfin-rpc/src/core/mod.rs
- jellyfin-rpc/src/core/rpc.rs
- jellyfin-rpc/src/lib.rs
- jellyfin-rpc/src/services/imgur.rs
- jellyfin-rpc/src/services/jellyfin.rs
- jellyfin-rpc/src/services/mod.rs
Add documentation for rustdoc so that the jellyfin-rpc crate isn't so barren on https://docs.rs/
> Add documentation for rustdoc

- Cargo.lock
- example.json
- jellyfin-rpc-cli/Cargo.toml
- jellyfin-rpc-cli/src/main.rs
- jellyfin-rpc/Cargo.toml
- jellyfin-rpc/example.json
- jellyfin-rpc/src/core/config.rs
- jellyfin-rpc/src/core/rpc.rs
- jellyfin-rpc/src/lib.rs
- jellyfin-rpc/src/services/imgur.rs
- jellyfin-rpc/src/services/jellyfin.rs
- jellyfin-rpc/src/tests.rs
fixes #85 
Add support for using self signed certificates through a new config option:
```json
{
"jellyfin": {
"self_signed_cert": true
}
}
```
Add `-s`/`--suppress-warnings` so these messages wont show up every time:
> Add support for self signed certificates (#85)

- jellyfin-rpc-cli/src/main.rs
- jellyfin-rpc/example.json
- jellyfin-rpc/src/core/config.rs
- jellyfin-rpc/src/core/mod.rs
- jellyfin-rpc/src/core/rpc.rs
- jellyfin-rpc/src/tests.rs
- scripts/installer.py
fixes #102 
This will allow you to hide the status when media is paused, it can be configured in the config like this
```json
{
...
"discord": {
...
"show_paused": false
...
}
...
}
```
> Add show_paused config option (#102)

- jellyfin-rpc-cli/src/main.rs
The title is pretty self explanatory, the loop that parses the buttons will break early whenever it reaches 2 entries.
This allows for stuff like this:
```json
"buttons": [
{
"name": "dynamic",
"url": "dynamic"
},
{
"name": "dynamic",
"url": "dynamic"
},
{
"name": "Cool Game :3",
"url": "https://store.steampowered.com/app/1718240"
}
]
```
Where the 3rd button is only shown if any of the dynamic buttons failed to be created for whatever reason
unsure if this actually needs to be documented anywhere, might be up for discussion
> Allow more than 2 RPC buttons in the config file

- .github/workflows/build.yml
- .github/workflows/release.yml
- jellyfin-rpc/example.json
- jellyfin-rpc/src/core/config.rs
- jellyfin-rpc/src/services/jellyfin.rs
- jellyfin-rpc/src/tests.rs
- scripts/installer.py
As visible from the title, this pull request adds the following:
- ARM support
I have tried the generated binary on raspberry pi 2b (ARMv7), and im fully hoping AARCH64 has backwards compatibility for 32-bit so we can call it full ARM support on linux xd. Stripping is done by emulating alpine linux to the armv7 arch because when i tried to strip it on a x64 bit system it failed.
- Formatting change
Now i am not quite sure if you will like this change, but i think having it in a format S1 - E1 is better than S1E1, but of course this is purely subjective
- Ommiting episode names
I find it quite clunky when the whole name is there, so i added an option to just have S1 - E1 instead of S1 - E1 Episode name
- Adding a leading 0
Last but not least, i added the option to append 0 to the season or …
> ARM support, ommiting episode names and adding a "0" prefix to episode and season numbers

- example.json
- jellyfin-rpc-cli/src/config.rs
- jellyfin-rpc-cli/src/main.rs
- jellyfin-rpc/src/jellyfin.rs
- jellyfin-rpc/src/lib.rs
- scripts/installer.py
Lets you customize how movies are displayed, exactly like how music is!
config example
```json
{
"jellyfin": {
"movies": {
"display": [
"year",
"critic-score",
"community-score",
"genres"
],
"separator": "|"
},
...
}
...
}
```
> Add Movie Display Options

- Cargo.lock
- jellyfin-rpc-cli/Cargo.toml
- jellyfin-rpc/src/lib.rs
This should avoid some logging issues when reporting bugs and also up the general security of the requests
> Use authorization header instead of adding to query

- jellyfin-rpc-cli/src/main.rs
Increasing from 3 to 7 to try and fix issues with pipe closing very often.
Fixes #137
> Change default wait time

- jellyfin-rpc/src/lib.rs
Fixes #150 
Adds a check for the enable_images variable in config when using imgur images
> Check if show_images is enabled before displaying imgur images

- jellyfin-rpc-cli/src/config.rs
- jellyfin-rpc-cli/src/main.rs
Fixes #162. This PR fixes an unclear function comment and adds a clean error exit to the failure to find a config file. I believe this is better for a user that hasn't made their config file yet or passing the wrong path parameter compared to just panicking.
Example run with missing main.json
```bash
> .\jellyfin-rpc.exe
2024-10-24 13:58:46 INFO  [jellyfin_rpc] Initializing Jellyfin-RPC
2024-10-24 13:58:47 ERROR [jellyfin_rpc] Config file could not be found at path: C:\Users\tronl\AppData\Roaming\jellyfin-rpc\main.json
2024-10-24 13:58:47 ERROR [jellyfin_rpc] Please create a proper config file: https://github.com/Radiicall/jellyfin-rpc/wiki/Setup
```
Example run with incorrect config parameter
```bash
> .\jellyfin-rpc.exe -c ./config.json
2024-10-24 14:03:21 INFO  [jellyfin_rpc] …
```
> Default config file name fixes

- Cargo.lock
- jellyfin-rpc-cli/Cargo.toml
- jellyfin-rpc-cli/src/config.rs
- jellyfin-rpc-cli/src/main.rs
- jellyfin-rpc/src/jellyfin.rs
- jellyfin-rpc/src/lib.rs
Solves #154 
- Add support for new `display` format for `music` and `movies`:
```jsonc
// [...]
"music": {
"display": {
"details_text": "{track}",
"state_text": "{artists} {sep} {genres}",
"image_text": "{album} ({year})"
},
"separator": "•"	    
},
"movies": {
"display": {
"details_text": "{title} ({year})",
"state_text": "{genres} {sep} {critic-score} {sep} {community-score}",
"image_text": "{title} ({year})"
},
"separator": "•"
},
// [...]
```
Music:
Movie:
Just for fun, another example config, with emojis:
```jsonc
// [...]
"music": {
"display": {
"details_text": "🎧 {track}",
"state_text": "👤 {artists} 🎭 {genres}",
"image_text": "💿 {album} ({year})"
},
"separator": "•"	    
},
"movies": {
"display": {
"details_text": "🎬 {title} ({year})",
"state_text": "🎭 {genres} {critic-score} …
```
> Implement custom activity text formatting

- .github/workflows/build.yml
- .github/workflows/release.yml
It seems updating apt while installing gcc is required, as when running test builds on my fork I get this in the build action
```E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/b/binutils/binutils-arm-linux-gnueabihf_2.42-4ubuntu2.3_amd64.deb  404  Not Found [IP: 52.252.163.49 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.```
> Fix timeout error when installing gcc for ubuntu arm 32/64

- .github/workflows/build.yml
- .github/workflows/release.yml
Fixes https://github.com/Radiicall/jellyfin-rpc/issues/180
Github Actions would build the x86_64 release as ARM64
> Fix Github building MacOS x86_64 as arm64
